[project]
authors = ["Charl P. Botha <cpbotha@vxlabs.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "aoc2024"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0.dev2024120105,<25"
